//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCM_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_DPP
    {
        public string ProID { get; set; }
        public string ProName { get; set; }
        public string ProJP { get; set; }
        public string ProTM { get; set; }
        public string PCName { get; set; }
        public string PUName { get; set; }
        public string PSName { get; set; }
    }
}
